export const types: any = {
  lucky7: "lucky7",
  lucky7B: "lucky7B",
  Queen: "queen",
  aaa: "AAA",
  ddb: "ddb",
  baccarat: "baccarat",
  baccarat2: "baccarat2",
  dt20: "dragontiger20A",
  card32: "card32a",
  Tp1Day: "Tp1Day",
  dt20b: "dt20b",
  onedaypoker: "onedaypoker",
  onedaypoker20: "onedaypoker20",
  teen20: "t20Odds",
  dragontiger1Day: "dragontiger1Day",
  dtl20: "dtl20",
  race2020: "race2020",
  poker6player: "poker6player",
  cmeter2020: "cmeter2020",
  Superover: "Superover",
  testtp: "testtp",
  Cards3J: "Cards3J",
  fivewicket: "fivewicket",
  card32b: "card32b",
  opentp: "opentp",
  cricket2020: "cricket2020",
  Andarbahar2: "Andarbahar2",
  Andarbahar: "Andarbahar",
  warcasino: "warcasino",
  worlimatka: "worlimatka",
  worliinstant: "worliinstant",
};

export const eventJson: any = {
  //@ts-ignore
  lucky7: () => import("../event-json/lucky7.json"),
  lucky7eu: () => import("../event-json/lucky7B.json"),
  queen: () => import("../event-json/queen.json"),
  Queen: () => import("../event-json/queen.json"),
  aaa: () => import("../event-json/AAA.json"),
  btable: () => import("../event-json/ddb.json"),
  baccarat: () => import("../event-json/baccarat.json"),
  baccarat2: () => import("../event-json/baccarat2.json"),
  dt20: () => import("../event-json/dt20.json"),
  card32: () => import("../event-json/card32.json"),
  teen: () => import("../event-json/Tp1Day.json"),
  dt202: () => import("../event-json/dt20b.json"),
  poker: () => import("../event-json/onedaypoker.json"),
  poker20: () => import("../event-json/onedaypoker20.json"),
  teen20: () => import("../event-json/teen20.json"),
  dt6: () => import("../event-json/dragontiger1Day.json"),
  dtl20: () => import("../event-json/dtl20.json"),
  race20: () => import("../event-json/race2020.json"),
  poker6: () => import("../event-json/poker6player.json"),
  cmeter: () => import("../event-json/cmeter2020.json"),
  superover: () => import("../event-json/Superover.json"),
  teen9: () => import("../event-json/testtp.json"),
  Cards3J: () => import("../event-json/Card3J.json"),
  cricketv3: () => import("../event-json/fivewicket.json"),
  card32eu: () => import("../event-json/card32b.json"),
  teen8: () => import("../event-json/opentp.json"),
  cmatch20: () => import("../event-json/cricket2020.json"),
  abj: () => import("../event-json/Andarbahar2.json"),
  ab20: () => import("../event-json/Andarbahar.json"),
  war: () => import("../event-json/warcasino.json"),
  worli: () => import("../event-json/worlimatka.json"),
  worli2: () => import("../event-json/worliinstant.json"),
  lucky5: () => import("../event-json/lucky6.json"),
  lucky7eu2: () => import("../event-json/lucky7C.json"),
  teen3: () => import("../event-json/instantp.json"),
  btable2: () => import("../event-json/btable2.json"),
  teen32: () => import("../event-json/instanttp2.json"),
  teen33: () => import("../event-json/instanttp3.json"),
  teen41: () => import("../event-json/queenTop.json"),
  ab3: () => import("../event-json/Andarbahar50.json"),
  aaa2: () => import("../event-json/aaa2.json"),
  teen20b: () => import("../event-json/teen20B.json"),
  teen20c: () => import("../event-json/teen20C.json"),
  teen42: () => import("../event-json/jackTop.json"),
  teenmuf: () => import("../event-json/teenpattiMuflis.json"),
  patti2: () => import("../event-json/Tp1card.json"),
  teensin: () => import("../event-json/baccarat29.json"),
  race17: () => import("../event-json/race17.json"),
  goal: () => import("../event-json/goal.json"),
  lucky15: () => import("../event-json/lucky15.json"),
  ballbyball: () => import("../event-json/ballbyball.json"),
  trio: () => import("../event-json/trio.json"),
  kbc: () => import("../event-json/kbc.json"),
  dum10: () => import("../event-json/dum10.json"),
  poison: () => import("../event-json/Poison1day.json"),
  poison20: () => import("../event-json/poison20.json"),
  joker20: () => import("../event-json/joker20.json"),
  cmeter1: () => import("../event-json/onecardmeter.json"),
  teen1: () => import("../event-json/onecard1Day.json"),
  race2: () => import("../event-json/race2.json"),
  notenum: () => import("../event-json/notenumber.json"),
  teen120: () => import("../event-json/oneCard20.json"),
  teen6: () => import("../event-json/teenpatti2.json"),
  trap: () => import("../event-json/trap.json"),
  roulette12: () => import("../event-json/beachRoulette.json"),
  roulette13: () => import("../event-json/roulette.json"),
  roulette11: () => import("../event-json/goldenRoulette.json"),
  mogambo: () => import("../event-json/mogambo.json"),
  dolidana: () => import("../event-json/dolidana.json"),
  teen62: () => import("../event-json/Vip3Patti1Day.json")
};
